name: Check PR

on: [pull_request]

jobs:
  run-ci:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Run Type Check & Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Compile GraphQL
        run: |
          if [[ "${{ github.head_ref }}" == "preview" ]]; then
            pnpm run compile-gql-test
          elif [[ "${{ github.head_ref }}" == "main" ]]; then
            pnpm run compile-gql-prod
          else
            echo "No GraphQL compilation step for branch ${{ github.head_ref }}"
          fi

      - name: Type Check
        run: |
          if [[ "${{ github.head_ref }}" == "main" || "${{ github.head_ref }}" == "preview" ]]; then
            pnpm type-check
          else
            echo "Skipping type-check as src/graphql/client is missing in the branch"
          fi

      - name: Check linting
        run: |
          if [[ "${{ github.head_ref }}" == "main" || "${{ github.head_ref }}" == "preview" ]]; then
            pnpm type-check
          else
            echo "Skipping linting as as src/graphql/client is missing in the branch"
          fi

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v6
