name: Check PR

on: [pull_request]

jobs:
  run-ci:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Run Type Check & Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # Compile GraphQL
      - name: Compile GraphQL for develop
        if: github.ref == 'refs/heads/develop'
        run: pnpm run compile-gql-dev

      - name: Compile GraphQL for preview
        if: github.ref == 'refs/heads/preview'
        run: pnpm run compile-gql-test

      - name: Compile GraphQL for main
        if: github.ref == 'refs/heads/main'
        run: pnpm run compile-gql-prod

      - name: Check types
        run: pnpm type-check

      - name: Check linting
        run: pnpm lint

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v6
